// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frfnraqbwtggrxofseja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZm5yYXFid3RnZ3J4b2ZzZWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNDg2NTgsImV4cCI6MjA1MTcyNDY1OH0.l6fulx5pLha6c6YhooG1hadns-WUyzv5SuFDQ2gUdIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);